name: Docker Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Construir imagen
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mi-proyecto-docker:latest .

      - name: Subir imagen
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mi-proyecto-docker:latest